#!/bin/sh
[ $# -eq 0 ] && { echo "$NO_ARGUMENTS_PASSED" && exit ; }
[ $1 == "--help" ] || [ $1 == "-h" ] && { echo "$HELP" && exit ; }
[ $(echo "$1" | cut -c1-1) == "-" ] && { echo "$INVALID_OPTION" && exit ; }
[ -f $1 ] || { echo "$FILE_MISSING" && exit ; }
interdiff -q "$1" /dev/null 2> /dev/null || echo "$INVALID_USAGE"
